export declare const SEMVER_PARTS: {
    major: 'major';
    minor: 'minor';
    patch: 'patch';
};
export declare const DISABLE_CACHE: {
    readonly headers: {
        readonly 'If-None-Match': "";
    };
};
export declare const VERSIONING_STRATEGIES: {
    semver: 'semver';
    calver: 'calver';
};
export declare const TAG_OBJECT_MESSAGE = "Tag generated by your friendly neighborhood Backstage Release Manager";
