import { Overrides } from '@material-ui/core/styles/overrides';
import { StyleRules } from '@material-ui/core/styles/withStyles';
import { AvatarClassKey, DependencyGraphDefaultLabelClassKey, DependencyGraphDefaultNodeClassKey, DependencyGraphEdgeClassKey, DependencyGraphNodeClassKey, DismissableBannerClassKey, EmptyStateClassKey, EmptyStateImageClassKey, MissingAnnotationEmptyStateClassKey, ErrorPanelClassKey, FeatureCalloutCircleClassKey, HeaderIconLinkRowClassKey, IconLinkVerticalClassKey, HorizontalScrollGridClassKey, LifecycleClassKey, MarkdownContentClassKey, LoginRequestListItemClassKey, LogViewerClassKey, OAuthRequestDialogClassKey, OverflowTooltipClassKey, GaugeClassKey, GaugeCardClassKey, ResponseErrorPanelClassKey, SelectInputBaseClassKey, SelectClassKey, ClosedDropdownClassKey, OpenedDropdownClassKey, SimpleStepperFooterClassKey, SimpleStepperStepClassKey, StatusClassKey, MetadataTableTitleCellClassKey, MetadataTableCellClassKey, MetadataTableListClassKey, MetadataTableListItemClassKey, StructuredMetadataTableListClassKey, StructuredMetadataTableNestedListClassKey, SupportButtonClassKey, TableFiltersClassKey, SubvalueCellClassKey, TableHeaderClassKey, TableToolbarClassKey, FiltersContainerClassKey, TableClassKey, TabBarClassKey, TabIconClassKey, TabsClassKey, TabClassKey, WarningPanelClassKey } from './components';
import { BottomLinkClassKey, BreadcrumbsClickableTextClassKey, BreadcrumbsStyledBoxClassKey, BackstageContentClassKey, ContentHeaderClassKey, ErrorPageClassKey, MicDropClassKey, HeaderClassKey, HeaderLabelClassKey, HeaderTabsClassKey, InfoCardClassKey, CardActionsTopRightClassKey, ItemCardGridClassKey, ItemCardHeaderClassKey, PageClassKey, SidebarClassKey, SidebarSpaceClassKey, SidebarSpacerClassKey, SidebarDividerClassKey, SidebarIntroClassKey, SidebarItemClassKey, SidebarPageClassKey, CustomProviderClassKey, SignInPageClassKey, TabbedCardClassKey, BoldHeaderClassKey, CardTabClassKey } from './layout';
declare type BackstageComponentsNameToClassKey = {
    BackstageAvatar: AvatarClassKey;
    BackstageDependencyGraphDefaultLabel: DependencyGraphDefaultLabelClassKey;
    BackstageDependencyGraphDefaultNode: DependencyGraphDefaultNodeClassKey;
    BackstageDependencyGraphEdge: DependencyGraphEdgeClassKey;
    BackstageDependencyGraphNode: DependencyGraphNodeClassKey;
    BackstageDismissableBanner: DismissableBannerClassKey;
    BackstageEmptyState: EmptyStateClassKey;
    BackstageEmptyStateImage: EmptyStateImageClassKey;
    BackstageMissingAnnotationEmptyState: MissingAnnotationEmptyStateClassKey;
    BackstageErrorPanel: ErrorPanelClassKey;
    BackstageFeatureCalloutCircular: FeatureCalloutCircleClassKey;
    BackstageHeaderIconLinkRow: HeaderIconLinkRowClassKey;
    BackstageIconLinkVertical: IconLinkVerticalClassKey;
    BackstageHorizontalScrollGrid: HorizontalScrollGridClassKey;
    BackstageLifecycle: LifecycleClassKey;
    BackstageMarkdownContent: MarkdownContentClassKey;
    BackstageLoginRequestListItem: LoginRequestListItemClassKey;
    BackstageLogViewer: LogViewerClassKey;
    OAuthRequestDialog: OAuthRequestDialogClassKey;
    BackstageOverflowTooltip: OverflowTooltipClassKey;
    BackstageGauge: GaugeClassKey;
    BackstageGaugeCard: GaugeCardClassKey;
    BackstageResponseErrorPanel: ResponseErrorPanelClassKey;
    BackstageSelectInputBase: SelectInputBaseClassKey;
    BackstageSelect: SelectClassKey;
    BackstageClosedDropdown: ClosedDropdownClassKey;
    BackstageOpenedDropdown: OpenedDropdownClassKey;
    BackstageSimpleStepperFooter: SimpleStepperFooterClassKey;
    SimpleStepperStep: SimpleStepperStepClassKey;
    BackstageStatus: StatusClassKey;
    BackstageMetadataTableTitleCell: MetadataTableTitleCellClassKey;
    BackstageMetadataTableCell: MetadataTableCellClassKey;
    BackstageMetadataTableList: MetadataTableListClassKey;
    BackstageMetadataTableListItem: MetadataTableListItemClassKey;
    BackstageStructuredMetadataTableList: StructuredMetadataTableListClassKey;
    BackstageStructuredMetadataTableNestedList: StructuredMetadataTableNestedListClassKey;
    BackstageSupportButton: SupportButtonClassKey;
    BackstageTableFilters: TableFiltersClassKey;
    BackstageSubvalueCell: SubvalueCellClassKey;
    BackstageTableHeader: TableHeaderClassKey;
    BackstageTableToolbar: TableToolbarClassKey;
    BackstageTableFiltersContainer: FiltersContainerClassKey;
    BackstageTable: TableClassKey;
    BackstageTabBar: TabBarClassKey;
    BackstageTabIcon: TabIconClassKey;
    BackstageTabs: TabsClassKey;
    BackstageTab: TabClassKey;
    BackstageWarningPanel: WarningPanelClassKey;
    BackstageBottomLink: BottomLinkClassKey;
    BackstageBreadcrumbsClickableText: BreadcrumbsClickableTextClassKey;
    BackstageBreadcrumbsStyledBox: BreadcrumbsStyledBoxClassKey;
    BackstageContent: BackstageContentClassKey;
    BackstageContentHeader: ContentHeaderClassKey;
    BackstageErrorPage: ErrorPageClassKey;
    BackstageErrorPageMicDrop: MicDropClassKey;
    BackstageHeader: HeaderClassKey;
    BackstageHeaderLabel: HeaderLabelClassKey;
    BackstageHeaderTabs: HeaderTabsClassKey;
    BackstageInfoCard: InfoCardClassKey;
    BackstageInfoCardCardActionsTopRight: CardActionsTopRightClassKey;
    BackstageItemCardGrid: ItemCardGridClassKey;
    BackstageItemCardHeader: ItemCardHeaderClassKey;
    BackstagePage: PageClassKey;
    BackstageSidebar: SidebarClassKey;
    BackstageSidebarSpace: SidebarSpaceClassKey;
    BackstageSidebarSpacer: SidebarSpacerClassKey;
    BackstageSidebarDivider: SidebarDividerClassKey;
    BackstageSidebarIntro: SidebarIntroClassKey;
    BackstageSidebarItem: SidebarItemClassKey;
    BackstageSidebarPage: SidebarPageClassKey;
    BackstageCustomProvider: CustomProviderClassKey;
    BackstageSignInPage: SignInPageClassKey;
    BackstageTabbedCard: TabbedCardClassKey;
    BackstageTabbedCardBoldHeader: BoldHeaderClassKey;
    BackstageCardTab: CardTabClassKey;
};
/** @public */
export declare type BackstageOverrides = Overrides & {
    [Name in keyof BackstageComponentsNameToClassKey]?: Partial<StyleRules<BackstageComponentsNameToClassKey[Name]>>;
};
export {};
